### ISSUE TITLE
Support consistent view of time-based visualizations across viewer timezones

### ISSUE THREAD

**Issue by jonmmease** [vegafusion/vegafusion#104]
## Overview
We would like the appearance of time-based charts to depend only on the `local_tz` argument provided to VegaFusion, not on the local timezone of the browser displaying the chart.

## Background
There are three general places where the local timezone matters:
 1. When loading datetimes values from strings (e.g. from JSON or CSV) strings without an explicit timezone (naive datetimes) are interpreted as being in local time and immediately converted into UTC milliseconds.
 2. Certain data transformations can operate in a local timezone mode. In particular, the [`timeunit`](https://vega.github.io/vega/docs/transforms/timeunit/) transform, and the use of [date part functions](https://vega.github.io/vega/docs/expressions/#datetime-functions) (e.g. `hours`, `months`, etc.) in the `formula` or `filter` transforms.
 3. Vega provides separate [quantitative scale types](https://vega.github.io/vega/docs/scales/#quantitative) for `local` and `utc` datetimes.

In practice, (2) and (3) should be either both local or both utc to create sensible charts. When using the `timeunit` parameter of an encoding channel in Vega-Lite, (2) and (3) are automatically aligned.

If (2) and (3) align, then there are 4 combinations to consider:
 - Load naive datetime values then transform in local mode (Naive-Local)
 - Load timezone-aware datetime values then transform in UTC mode (Aware-UTC)
 - Load naive datetime values then transform in UTC mode (Naive-UTC)
 - Load timezone-aware datetime values then transform in local mode (Aware-Local)

## Examples
Here are simple Vega-Lite examples of all for combinations. Images generated in the [America/New_York](https://www.zeitverschiebung.net/en/timezone/america--new_york) timezone.

### Naive-Local
https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289ADkkNUvwAybKEkGKMcGmSxoxABiXKkmFKlDErDNWgA2qDumHBoIABMzpGR-M5i8QAsAAQAjGmoaWKozs4gAL4KIR7h6NGx8YnOqWmRWTl5hcUqpREVcQnJ6QDMDbn5BQC6RSDI6gDWEThsNLKYNnCyUGzKc2RooACemyA6CHAAqrJ0ETBsDOoQNgBmNHCCyhGh4UpIAB401957NFATAGELvM0JFRjpMIIyr8DoUCgUgA

![Naive-Local](https://user-images.githubusercontent.com/15064365/166898197-b645419c-77d0-425e-a826-3c88b125b811.png)

### Aware-UTC
https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEA7knVx+AVQAqAYUUY4NMljRiADEuVJMKVKGJJBBjU0AG1QT0w4NBAAJlcYmP5XMSSAFgACAEZM1EyxVFdXAC0QAF8FcK8o9DiEpJTXDMyY3PzCkvLKyOjaxOS0rIBmVoLisoBdcpBkdQBraJw2GllMOzhZKDZlZbI0UABPPZAdBDhzWTpohkxYNgZ1CDsAMxo4QWVoiKilJAAPGkevmONCgs2sdxWaBiUx0mEE1WBpzKpVKQA

![Aware-UTC](https://user-images.githubusercontent.com/15064365/166898228-bfdd3b78-7061-41f4-82c8-942fddad8c20.png)

### Naive-UTC
https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289ADkkNUvwCqAFQDCijHBpksaMQAYlypJhSpQxJIIZqaADaoO6YcGggAEzOUVH8zmIJACwABACM6ajpYqjOziAAvgqhHhHoMXEJSc5p6VHZuflFJSplkZXxiSkZAMyNeQWFALrFIMjqANaROGw0spg2cLJQbMrzZGigAJ5bIDoIcKaydJEMmLBsDOoQNgBmNHCCypFhEUpIAB40t977NFBJpYrgs0FExjpMIJyv9DkVCoUgA

![Naive-UTC](https://user-images.githubusercontent.com/15064365/166898246-471a0e8f-b456-4eac-8d27-2fc5f591d7be.png)

### Aware-Local
https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEA7knVx+AGTZQkgxRjg0yWNGIAMS5UkwpUoYjYY1NABtUE9MODQQACZXaOj+VzFEgBYAAgBGDNQMsVRXVwAtEABfBTCvSPRY+MTk13SM6Jy8guKyioiomoSk1MyAZhb8otKAXTKQZHUAayicNhpZTDs4WSg2ZSWyNFAAT12QHQQ4AFVZOiiYNgZ1CDsAMxo4QWUo8MilJAAPGnvfI40KAzADCN2WaGikx0mEEVUBJ1KJRKQA

![Aware-Local](https://user-images.githubusercontent.com/15064365/166898260-55f0bc62-d2a4-4419-98a2-19dfeb3947ce.png)

## Current VegaFusion behavior
VegaFusion is capable of evaluating steps (1) and (2) above on the server, and to do so it will use the provided `local_tz` parameter to determine what is considered to be the local timezone.  Datetime values in the transformed dataset are serialized and sent to the client as UTC milliseconds.  As long as the provided `local_tz` matches the browser's local timezone, this approach will exactly match the behavior when using plain Vega (without VegaFusion).

The trouble is when the browser's local timezone does not match the `local_tz` argument. In this case we would like the chart to match what plain Vega would produce if the browser were in the `local_tz` timezone.  But we currently have inconsistent behavior.

As of VegaFusion 0.3.0, datetime columns that result from (1) and (2) are always serialized as UTC milliseconds. This gives the desired behavior for the `Naive-UTC` and `Aware-UTC` scenarios because in these cases step (3) does not use local time at all, and so the same result will be displayed regardless of the browser timezone.

However, this results in inconsistent behavior for the `Naive-Local` and `Aware-Local` scenarios.  In these cases, step (3) does use the browsers local timezone and so the serialized UTC values are converted into the browsers local timezone. This means that viewers in different timezones will see results displayed differently. Even worse, in the `Naive-Local` case, VegaFusion and Vega in the browser will perform UTC conversions relative to different local timezones, resulting in inconsistent behavior.

## Proposed updates
My proposal is to update VegaFusion so that datetimes are serialized as naive datetime strings **if** we can determine that step (3) is in local timezone mode.  Otherwise, serialize to UTC milliseconds as we currently do.

Serializing to a naive datetime string involves converting the UTC millisecond value to the `local_tz` timezone and then converting to a naive datetime string.

I haven't fully worked through the details, but I'm optimistic that we will be able to detect whether (3) is in local mode by checking which scale a datetime value is encoded with and then checking whether that scale is in local or utc mode.

With this one change, I believe we will have the desired behavior in all cases.

**Comment by jonmmease** [comment]
My current plan is to implement this logic as a planning pass.  The end result of this planning pass would be to append transforms to the end of select data specifications of the form

```json
{"type": "formula", "expr": "timeFormat(datum.date, '%Y-%m-%d %H:%M:%S.%L')", "as": "date"},
```
(PR https://github.com/vegafusion/vegafusion/pull/105 is needed first to add support for the `timeFormat` expression function)

This transform has the effect of replacing a column (named `date` in this case) of datetime values (in UTC millisecond form) with a column of naive datetime strings in the local timezone.

**Comment by jkillian** [comment]
Just read over the proposal - the solution seems being fairly elegant and straightforward, I like it! To summarize my understanding, whenever we have a situation where we have local  axis/scales, VegaFusion will produces “naive” datetime strings so that the client considers them to be in the local timezone and thus they show up the same for all users. This seems like it generally would work to me!

I do wonder about a couple less usual edge cases. For example, if one of these naive datetime strings fell on a daylight saving's gap for one client but not for another, what would happen? Might be interesting to try something like Sunday, March 13th, 2022, 2:30am in both America/New_York and America/Phoenix and see if any issues arise.

**Comment by jonmmease** [comment]
Yeah, datetimes on daylight savings boundaries could still produce inconsistent results across viewer timezones. I don't think there will be a way around that without significant changes to Vega (e.g. https://github.com/vega/vega/issues/3482).  

I think this will only come up when binning by hour (at least I don't think any of the daylight savings boundaries cross midnight), or not binning at all. We will want to double check what happens at these boundaries to make sure there aren't errors.

**Comment by jkillian** [comment]
I imagine there might be a few other oddities, such as if timezones made other non-DST related changes, but I suspect these are rare enough that it shouldn't be a huge issue. I suppose an alternative solution, like writing everything out in "UTC" (that is, an adjusted UTC timestamp that will really end up making things look as if it were in the user's desired timezone), and then rewriting the user's spec so that all date part functions and `timeunit` are using the UTC variant, might handle these abnormalities slightly better since then the client's local timezone will never come into play. But it sounds reasonably more complex and likely not worth it.

**Comment by jonmmease** [comment]
>  I suppose an alternative solution, like writing everything out in "UTC" (that is, an adjusted UTC timestamp that will really end up making things look as if it were in the user's desired timezone), and then rewriting the user's spec so that all date part functions and timeunit are using the UTC variant, might handle these abnormalities slightly better since then the client's local timezone will never come into play

I think this would essentially transform Naive-Local to Naive-UTC and Aware-Local to Aware-UTC. This would result in consistent appearance across viewer timezones, but it wouldn't be consistent with the original spec even in the authors own timezone.

**Comment by jonmmease** [comment]
Done in #105
