### ISSUE TITLE
Projection Pushdown: Determine fields used by vlSelectionTest

### ISSUE THREAD

**Issue by jonmmease** [vegafusion/vegafusion#115]
As a follow-on to #113, it would improve the utility of projection pushdown if we were able to precisely determine which columns are used by `vlSelectionTest` expressions.

For example, consider the Vega-Lite spec:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "Drag out a rectangular brush to highlight points.",
  "data": {"url": "data/cars.json"},
  "params": [{
    "name": "brush",
    "select": "interval"
  }],
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
      "condition": {"param": "brush", "field": "Cylinders", "type": "ordinal"},
      "value": "grey"
    }
  }
}
```
![Screenshot_20220526_151912](https://user-images.githubusercontent.com/15064365/170561145-3a3ad971-1e13-40b6-9833-94ecf9bd51fc.png)

With selection
![Screenshot_20220526_152045](https://user-images.githubusercontent.com/15064365/170561386-64d66b60-2059-4579-8783-5a8b1d064d1c.png)

In the generated Vega, the coloring of the symbols is controlled by the selection with:

```json
          "stroke": [
            {
              "test": "!length(data(\"brush_store\")) || vlSelectionTest(\"brush_store\", datum)",
              "scale": "color",
              "field": "Cylinders"
            },
            {"value": "grey"}
          ],
```
The question is which columns of `datum` are used by the expression `vlSelectionTest(\"brush_store\", datum)`. To find out, in general, we need to know the contents of the `brush_store` dataset.  

In this case, the definition of `brush_store` is empty:
```json
{"name": "brush_store"},
```
Rows are added to `brush_store` dynamically in the following signal update expression:
```json
    {
      "name": "brush_modify",
      "on": [
        {
          "events": {"signal": "brush_tuple"},
          "update": "modify(\"brush_store\", brush_tuple, true)"
        }
      ]
    }
```
The row that is added is actually added is defined as `brush_tuple`:
```json
    {
      "name": "brush_tuple",
      "on": [
        {
          "events": [{"signal": "brush_Horsepower || brush_Miles_per_Gallon"}],
          "update": "brush_Horsepower && brush_Miles_per_Gallon ? {unit: \"\", fields: brush_tuple_fields, values: [brush_Horsepower,brush_Miles_per_Gallon]} : null"
        }
      ]
    },
```

The part we actually care about, though, is the `brush_tuple_fields` value, which is defined as:

```json
    {
      "name": "brush_tuple_fields",
      "value": [
        {"field": "Horsepower", "channel": "x", "type": "R"},
        {"field": "Miles_per_Gallon", "channel": "y", "type": "R"}
      ]
    },
```
This means that the fields that `vlSelectionTest(\"brush_store\", datum)` uses are "Horsepower" and "Miles_per_Gallon".

So the question is, is there a reliable way to determine this based on inspection of the Vega specification.

**Comment by jonmmease** [comment]
cc @domoritz. Have you given thought to whether there's a reliable way to look at a Vega spec and identify which datum columns a `vlSelectionTest` expression uses?

**Comment by domoritz** [comment]
We have an expression parser in Vega that can help here. I think I implemented something where I visit the AST in https://github.com/vega/vega-lite/blob/acc4f6b0b9668a925213b59a12301e53478dcbb6/src/compile/data/expressions.ts#L29.

**Comment by jonmmease** [comment]
initial version done in https://github.com/vegafusion/vegafusion/pull/117

**Comment by domoritz** [comment]
Great. We don't have immediate plans to change the way we generate expressions for selections but the format is definitely not a strict contract.

**Comment by jonmmease** [comment]
Yeah, understood.  Thanks!
