### ISSUE TITLE
Support Colab

### ISSUE THREAD

**Issue by jonmmease** [vegafusion/vegafusion#55]
I tried `vegafusion-jupyter==0.0.1a1` in Google Colab. Colab is successfully able to load the extension from a CDN, and the widget is displayed

<img width="273" alt="Screen Shot 2022-01-17 at 11 53 58 AM" src="https://user-images.githubusercontent.com/15064365/149810145-b8ef9e6c-1ee5-4204-b664-0628f5702fca.png">

But the comm message is not successfully sent from the client to the server. Here is the browser console message

<img width="452" alt="Screen Shot 2022-01-17 at 11 53 40 AM" src="https://user-images.githubusercontent.com/15064365/149810123-cfeeda20-b8a2-4c9e-b196-9f1c32aa89ad.png">

There's not a lot to go on to debug this unforntunately

**Comment by dwootton** [comment]
One comment on here for anyone using it in colab, you'll need to add `vegafusion-python-embed` to the packages to install.
Following the quick start in the readme, your pip install will become:
`pip install vegafusion-jupyter vega-datasets vegafusion-python-embed`

[Example Colab here](https://colab.research.google.com/drive/11uW3T6nR_29sZBYbFdiztaZY_kr9QXx3?usp=sharing)

Thanks @jonmmease for solving this bug before I even ran into it 👍
