### ISSUE TITLE
Provide the VegaFusionRunTime from the vegafusion package

### ISSUE THREAD

**Issue by MarcSkovMadsen** [vegafusion/vegafusion#68]
The only dependency the `panel-vegafusion` python package has to vegafusion python packages is the import of the `vegafusion_jupyter.runtime`. 

![image](https://user-images.githubusercontent.com/42288570/151708548-66d3e2c1-611a-410c-8a28-c955780255b4.png)

The `runtime` is an instance of the `VegaFusionRunTime` defined in `vegafusion_jupyter`. 

![image](https://user-images.githubusercontent.com/42288570/151708590-3d4c0373-8351-479c-bb06-7e0794f9eac2.png)

I believe its more natural that the `VegaFusionRunTime` is defined in the `vegafusion` package. In that way integration libraries have a more simple and natural dependency.

If not it would make sense for me to copy the `VegaFusionRunTime` implementation to `panel-vegafusion` package and drop the dependency on `vegafusion_jupyter`. 

Please let me know what you would prefer @jonmmease ? Thanks.

**Comment by jonmmease** [comment]
Yeah, there are a couple of things that should be moved out of `vegafusion-jupyter`.  In addition to the runtime, the data transformer that writes DataFrames as feather files will apply across extension types.

Right now `vegafusion-python` is a pure Rust package and I haven't yet worked through how to combine pure Python modules in the same package.  I doubt it's that difficult, but I haven't tried.  In any case, I'd say go ahead and copy over what you need right now, and that will help inform the refactoring later.
