### ISSUE TITLE
Move feather transformer to 'vegafusion' package

### ISSUE THREAD

**Issue by MarcSkovMadsen** [vegafusion/vegafusion#70]
I need the Altair `vegafusion-feather` renderer for `panel-vegafusion`. Currently its in `vegafusion_jupyter` which means I will have that as a dependency.

I believe it should only be nescessary to depend on the `vegafusion` library ??.

## Context

I need it to enable the communication.

![image](https://user-images.githubusercontent.com/42288570/151743041-0208ddad-dc1b-4889-aff3-f155d9938457.png)

**Comment by jonmmease** [comment]
Similar to #68

**Comment by jonmmease** [comment]
Done in #72. This functionality is in a new `vegafusion` package.
