### ISSUE TITLE
Support multiple 'vegafusion' renderers.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [vegafusion/vegafusion#71]
The jupyter `VegaFusionWidget` widget depends on the `vegafusion` renderer and `vegafusion-feather` transformer.

![image](https://user-images.githubusercontent.com/42288570/151743215-fbfb40bb-54e8-4eae-b736-3c1c56ea6122.png)

For `panel-vegafusion` I want to be able to drop the dependency on `vegafusion_jupyter` and provide a `panel-vegafusion` renderer.

Right now its *hard-coded* that the `vegafusion-transformer` supports the `vegafusion` renderer only.

![image](https://user-images.githubusercontent.com/42288570/151743421-55ad2096-53d0-4711-b0e5-3ea95f0e4ddd.png)

## Solution

Change to

![image](https://user-images.githubusercontent.com/42288570/151743522-221d5fbe-d73b-4059-91ba-f29b8ac07121.png)

or support some mechanism for "plugging" in alternative renderers.

I would like to call my renderer 'panel-vegafusion'.

**Comment by jonmmease** [comment]
Done in #72
