### ISSUE TITLE
[FeatureRequest] `conda` package

### ISSUE THREAD

**Issue by dhirschfeld** [vegafusion/vegafusion#73]
Are there plans to provide a `conda` package? If not I might take a crack at it some point myself (next few months) as it would make it significantly easier for me to try it out.

- [x] [`vegafusion-python-embed`](https://pypi.org/project/vegafusion-python-embed/)
      - https://github.com/conda-forge/staged-recipes/pull/18081
      - https://github.com/conda-forge/vegafusion-python-embed-feedstock
- [x] [`vegafusion`](https://pypi.org/project/vegafusion/)
      - https://github.com/conda-forge/staged-recipes/pull/18272
      - https://github.com/conda-forge/vegafusion-feedstock
- [x] [`vegafusion-jupyter`](https://pypi.org/project/vegafusion-jupyter/)
      - https://github.com/conda-forge/staged-recipes/pull/18281
      - https://github.com/conda-forge/vegafusion-jupyter-feedstock

**Comment by jonmmease** [comment]
Hi @dhirschfeld, yes a conda-forge package is on the [roadmap](https://vegafusion.io/roadmap.html#conda-forge-packages), but no one has started on it yet so any help would be very welcome!  A good starting point would be to find an existing rust+Python conda-forge recipe that uses the [maturin](https://github.com/PyO3/maturin) build tool. e.g https://github.com/conda-forge/staged-recipes/search?q=maturin&type=issues.

**Comment by dhirschfeld** [comment]
One example recipe: https://github.com/conda-forge/ripfind-feedstock/blob/18bf976743d6db653024a3af0812cb17c1eac3c2/recipe/meta.yaml

Not sure it's a better example that any other but it was recommended by [`isuruf`](https://gitter.im/conda-forge/conda-forge.github.io?at=620d9f9e51bd8b580ca96a95)

**Comment by jonmmease** [comment]
Thanks!  I'm going to take a look at this today

**Comment by jonmmease** [comment]
Starting work on the  `vegafusion-python-embed` package (the one that wraps the Rust logic) over in https://github.com/conda-forge/staged-recipes/pull/18081 if you want to take a look.

After this one is published, two additional pure Python packages that depend on this will need to be published ([`vegafusion`](https://pypi.org/project/vegafusion/) and [`vegafusion-jupyter`](https://pypi.org/project/vegafusion-jupyter/)).

**Comment by jonmmease** [comment]
Adding sdist packages in https://github.com/vegafusion/vegafusion/pull/74. These will be the inputs for the corresponding conda-forge packages.

**Comment by dhirschfeld** [comment]
Closing as resolved :rocket:

Thanks @jonmmease!

**Comment by jonmmease** [comment]
Thanks for the support @dhirschfeld!

**Comment by jonmmease** [comment]
BTW, I'm planning to release version 0.1.0 this afternoon, so that will be a chance to practice updating the conda packages. Let me know if you run into anything with the initial, version 0.0.4, conda packages.
